###
POST http://localhost:8080/transaction/bankPaymentPayment/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg2NDcyOTEsImV4cCI6MTY1ODg2MzI5MSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyODJhZDE4MjFmYzExNTAxODIxZmMxNDBkZjAwMDAiLCJyb2xlIjoiUk9MRV9BRE1JTiJ9.ChE-a7KI8bm5E0TSWHXAQpzf9DJF0ca3chTzM3CvSa4

{
  "transferId": "8a8a85f182257a580182257b9b850004"
}

###

GET http://localhost:8080/transaction/bankPayment/getTransaction?cardId=4028d6d1822078bf01822078ea8a0000&page=0&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg2NzI0ODAsImV4cCI6MTY1ODg4ODQ4MCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyOGQ2ZDE4MjIwMzJhNDAxODIyMDM1MmMzMjAwMDAiLCJyb2xlIjoiUk9MRV9QQVlNRU5UIn0.JtW9-wmbstNqw-jPTaQ_ysUKQvEyod4JntSeDfRHdmI

###

GET http://localhost:8080/transaction/bankPayment/getTransactionByCardNumber?cardNumber=8600682267453961&page=0&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg2NzI0ODAsImV4cCI6MTY1ODg4ODQ4MCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyOGQ2ZDE4MjIwMzJhNDAxODIyMDM1MmMzMjAwMDAiLCJyb2xlIjoiUk9MRV9QQVlNRU5UIn0.JtW9-wmbstNqw-jPTaQ_ysUKQvEyod4JntSeDfRHdmI

###

GET http://localhost:8080/transaction/bankPayment/getTransactionByProfileId?clientId=40282ad1821fc32a01821fc57ea60004&page=0&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg2NzI0ODAsImV4cCI6MTY1ODg4ODQ4MCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyOGQ2ZDE4MjIwMzJhNDAxODIyMDM1MmMzMjAwMDAiLCJyb2xlIjoiUk9MRV9QQVlNRU5UIn0.JtW9-wmbstNqw-jPTaQ_ysUKQvEyod4JntSeDfRHdmI

###

GET http://localhost:8080/transaction/bankPayment/getTransactionByPhone?phone=998972198989&page=0&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg2NzI0ODAsImV4cCI6MTY1ODg4ODQ4MCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyOGQ2ZDE4MjIwMzJhNDAxODIyMDM1MmMzMjAwMDAiLCJyb2xlIjoiUk9MRV9QQVlNRU5UIn0.JtW9-wmbstNqw-jPTaQ_ysUKQvEyod4JntSeDfRHdmI


###

GET http://localhost:8080/transaction/bankPayment/getCreditCardId?cardId=4028d6d1822078bf01822078ea8a0000&page=0&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg2NzI0ODAsImV4cCI6MTY1ODg4ODQ4MCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyOGQ2ZDE4MjIwMzJhNDAxODIyMDM1MmMzMjAwMDAiLCJyb2xlIjoiUk9MRV9QQVlNRU5UIn0.JtW9-wmbstNqw-jPTaQ_ysUKQvEyod4JntSeDfRHdmI


###

GET http://localhost:8080/transaction/bankPayment/getDebitCardId?cardId=4028d6d18220dcb9018220e013370000&page=0&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg2NzI0ODAsImV4cCI6MTY1ODg4ODQ4MCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyOGQ2ZDE4MjIwMzJhNDAxODIyMDM1MmMzMjAwMDAiLCJyb2xlIjoiUk9MRV9QQVlNRU5UIn0.JtW9-wmbstNqw-jPTaQ_ysUKQvEyod4JntSeDfRHdmI


###

GET http://localhost:8080/transaction/bankPayment/getDebitCreditByMonthly?month=7&page=0&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg2NzI0ODAsImV4cCI6MTY1ODg4ODQ4MCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyOGQ2ZDE4MjIwMzJhNDAxODIyMDM1MmMzMjAwMDAiLCJyb2xlIjoiUk9MRV9QQVlNRU5UIn0.JtW9-wmbstNqw-jPTaQ_ysUKQvEyod4JntSeDfRHdmI

###
#eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg2NDcyOTEsImV4cCI6MTY1ODg2MzI5MSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyODJhZDE4MjFmYzExNTAxODIxZmMxNDBkZjAwMDAiLCJyb2xlIjoiUk9MRV9BRE1JTiJ9.ChE-a7KI8bm5E0TSWHXAQpzf9DJF0ca3chTzM3CvSa4